version: '3.9'

services:
  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: csse
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/venv
    env_file:
      - .env

volumes:
  pgdata: {}
