version: '3.9'

services:
  backend:
    container_name: csse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/venv
    env_file:
      - .env
